# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vox_id', models.BigIntegerField(null=True, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('modified', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vox_id', models.BigIntegerField(null=True, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('pattern', models.CharField(blank=True, max_length=255)),
                ('modified', models.DateTimeField(null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voximplant.Application')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Scenarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vox_id', models.BigIntegerField(null=True, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('modified', models.DateTimeField(null=True)),
                ('file', models.FilePathField(path='/home/telminov/git/pbx-voximplant/vox_scripts')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
