# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voximplant', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scenarios',
            new_name='Scenario',
        ),
    ]
