# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voximplant', '0002_auto_20160513_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scenario',
            old_name='file',
            new_name='file_path',
        ),
    ]
