# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 18:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('voximplant', '0003_auto_20160513_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='uploaded',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 13, 18, 46, 31, 896756, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rule',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 13, 18, 46, 35, 497012, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scenario',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 13, 18, 46, 37, 129260, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
