# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voximplant', '0004_auto_20160513_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='scenarios',
            field=models.ManyToManyField(related_name='rules', to='voximplant.Scenario'),
        ),
    ]
