# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 08:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voximplant', '0007_auto_20160514_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllistphone',
            name='completed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='calllist',
            name='canceled',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calllist',
            name='completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calllist',
            name='name',
            field=models.CharField(default='call_list', max_length=255),
        ),
        migrations.AlterField(
            model_name='calllist',
            name='started',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calllistphone',
            name='attempts_left',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calllistphone',
            name='call_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='voximplant.CallList'),
        ),
        migrations.AlterField(
            model_name='calllistphone',
            name='result_data_json',
            field=models.TextField(blank=True),
        ),
    ]
