# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voximplant', '0008_auto_20160514_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calllist',
            name='completed',
        ),
        migrations.AddField(
            model_name='calllist',
            name='downloaded',
            field=models.DateTimeField(blank=True, help_text='Last datetime of checking state from VoxImplant', null=True),
        ),
        migrations.AlterField(
            model_name='calllistphone',
            name='completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
