# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voximplant', '0009_auto_20160516_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='uploaded',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='uploaded',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='vox_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='vox_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
