# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voximplant', '0010_auto_20160516_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(default='.voximplant.com', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='uploaded',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calllistphone',
            name='status',
            field=models.CharField(blank=True, choices=[('', ''), ('New', 'New'), ('In progress', 'In progress'), ('Processed', 'Processed'), ('Error', 'Error')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rule',
            name='pattern',
            field=models.CharField(default='.*', max_length=255),
        ),
        migrations.AlterField(
            model_name='rule',
            name='uploaded',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
