# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-21 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voximplant', '0011_auto_20160516_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllistphone',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calllistphone',
            name='status',
            field=models.CharField(blank=True, choices=[('', ''), ('New', 'New'), ('In progress', 'In progress'), ('Cancelled', 'Cancelled'), ('Processed', 'Processed'), ('Error', 'Error')], max_length=50),
        ),
    ]
