# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voximplant', '0012_auto_20160721_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='file_path',
            field=models.FilePathField(path='/home/telminov/git/broadcast/vox_scripts'),
        ),
    ]
